### PR TITLE
Reorganize sources and move to Meson

### PR DESCRIPTION
**Pull request by arteymix**
Meson is actually very good at this because it does not implicitly add `glib-2.0` and `gobject-2.0`, so a simple project would just be replacing them with the posixified ones.

I also reorganized the project to look more like a posix stub of glib-2.0 and gobject-2.0.

### CODE REVIEW

**Comment by arteymix** [comment]
Here's how it looks once installed:

```
tmp
└── usr
    └── local
        ├── include
        │   └── glib-posix-2.0
        │       ├── glib
        │       │   ├── glib-error.h
        │       │   ├── glib-list.h
        │       │   └── glib-string.h
        │       ├── glib.h
        │       ├── glib-object.h
        │       └── gobject
        │           └── gvaluecollector.h
        ├── lib64
        │   └── pkgconfig
        │       ├── glib-posix-2.0.pc
        │       └── gobject-posix-2.0.pc
        └── share
            └── vala
                └── vapi
                    ├── glib-posix-2.0.deps
                    ├── glib-posix-2.0.vapi
                    ├── gobject-posix-2.0.deps
                    └── gobject-posix-2.0.vapi
```

From a developer perspective:

```meson
project('foo', 'c', 'vala')

glib_dep = dependency('glib-posix-2.0')
gobject_dep = dependency('gobject-posix-2.0')

executable('main', 'main.vala', dependencies: [glib_dep, gobject_dep])
```

**Comment by Maijin** [comment]
See https://github.com/radare/radare2

**Comment by radare** [comment]
I think both builds can coexist. Is gnome killing autotools completelly?

**Comment by arteymix** [comment]
@radare I don't think so, it will take a while before Meson can fully replace it. That would mean converting all projects, possibly working the missing parts on jhbuild, package distribution, etc... It's up to maintainers to choose and it's good that GNOME is providing infrastructure for it

I can reintroduce back the Make-based build, but it does not have much value at this point: anything that could have been done with it is covered with Meson. Plus, we now have subproject support.

Also, the posixvalac thing is basically a hack for building sources in two steps. Anyone who would use something similar would either make it explicit in its Makefile or use Meson/Autotools.

```make
%.c: %.vala
    valac --ccode --pkg=glib-posix-2.0 --pkg=gobject-posix-2.0 $<

main: foo.c bar.c
    ${CC} -o $@ $(shell pkg-config --cflags --libs glib-posix-2.0 gobject-posix-2.0) $^
```

The emscripten thing is really nice and maybe we should have an example folder for all the magic we can do with posixvala.

**Comment by radare** [comment]
I would prefer not to kill the configure / makefiles yet. Im happy with including meson, im currently doing that for r2, but both can coexist and posixvala is not didnt changed too much in a lot of time so its easy to maintain. Can you update the pr bringing back acr and make?

**Comment by arteymix** [comment]
Sure, I'll revive it.

Do you want to keep the previous layout or should I update the Makefile?

**Comment by radare** [comment]
Changing the layout is ok. I dont really use vala in my daily life. So its ok to bend some things for people using it.

**Comment by radare** [comment]
out of curiosity, are you using posixvala for something? :D

**Comment by arteymix** [comment]
I'm considering working on reintroducing a posix mode into Vala by layering the C codegen to make GLib optional. You can read more about it here: https://mail.gnome.org/archives/vala-list/2017-May/msg00005.html

It's a lot of work, so posixvala represents a good solution in the meantime.

Thus, no, but possibly! I would like to experiment with Emscripten and Valum eventually :)

**Comment by radare** [comment]
ping me when ready

**Comment by radare** [comment]
That is awesome! the main reason for doing posixvala was to be able to use vala for those purposes. i just felt like the vala project at the time was so stalled and the reason for removing the posix backend was that the language was designed to focus on glib, so all the other forks that target JS, c#, objc… basically died.

So having all this stuff coming back again sounds good to me, all my support +1

**Comment by arteymix** [comment]
@radare 

I think I'll maintain a fork instead and submit patches (see #12) because I plan to change quite significantly the structure and it will be difficult to maintain two build systems.

**Pull request closed without merging**
