### PR TITLE
make GQuark unsigned long so pointer fits into it

### PR DESCRIPTION
**Pull request by rofl0r**
..even on 64bit.

### CODE REVIEW

**Comment by radare** [comment]
On windows, long is 32bit even on 64 bits. So i would probably go for size_t or unsigned long long

**Comment by rofl0r** [comment]
oh i didn't know anyone cares for windows. in that case the safest type to use is uintptr_t (requires inclusion of header that defines it).

**Comment by rofl0r** [comment]
new version in #10

**Comment by radare** [comment]
You can push -f in the same pr and it will be updated properly

**Comment by rofl0r** [comment]
yes, but not from the github interface, and i was too lazy to check out the repo from the shell.

**Comment by radare** [comment]
Yeah np :) just a side note. Thx

**Pull request closed without merging**
